#!/usr/bin/env python3
"""Encode a four-bank footer in the SAME 188 reclaimed diagnostic bytes.
No assembler relaxation, new SRAM allocation, or firmware flash modification.
"""
from pathlib import Path
import struct, re, json, sys
ROOT=Path(__file__).resolve().parents[1]
BASE=0x36c7c; START=BASE+72; END=BASE+188
def i24(v): return v.to_bytes(3,'little')
def jump(pc,dst):
    d=dst-pc-4
    assert -(1<<17)<=d<(1<<17)
    return i24(6|((d&0x3ffff)<<6))
def lr(pc,r,dst):
    d=dst-((pc+3)&~3)
    assert d%4==0 and -0x40000<=d<0
    return i24(1|(r<<4)|(((d//4)&65535)<<8))
def load(r,b,off=0): return i24(2|(r<<4)|(b<<8)|(2<<12)|((off//4)<<16))
def store(r,b): return i24(2|(r<<4)|(b<<8)|(6<<12))
code=bytearray()
def emit(b): code.extend(b)
def literal(r,n): emit(lr(START+len(code),r,BASE+4*n))
def memw(): emit(bytes.fromhex('c02000'))
literal(8,0);memw();emit(load(9,8))
literal(10,1);literal(11,2);literal(12,3);literal(13,4)
emit(bytes.fromhex('0c4e'))  # movi.n a14,4
loop=START+len(code)
emit(load(15,13));emit(store(15,8));memw()
emit(load(15,13,4));emit(store(15,10));memw()
emit(load(15,13,8));emit(store(15,11));memw();emit(store(15,12));memw()
emit(i24(2|(13<<4)|(13<<8)|(12<<12)|(12<<16))) # addi a13,a13,12
emit(i24(2|(14<<4)|(14<<8)|(12<<12)|(255<<16))) # addi a14,a14,-1
pc=START+len(code);delta=loop-pc-4
assert -128<=delta<128
emit(i24(0x56|(14<<8)|((delta&4095)<<12))) # bnez a14,loop
emit(store(9,8));memw();literal(12,5)
emit(bytes.fromhex('880c1b88890c0c1dd24764'))
emit(jump(START+len(code),0x2c291))
while len(code)%4: emit(b'\0')
CANARY_FN=START+len(code)
canary=lr(CANARY_FN,8,BASE+20)+bytes.fromhex('0c19926800c020001df0')
assert len(canary)==13
COUNTER=(CANARY_FN+len(canary)+3)&~3
assert COUNTER+4<=END,(hex(COUNTER),len(code))
data=bytearray(struct.pack('<6I',0x01130800,0x011089bc,0x0110935c,0x0113b14c,BASE+24,COUNTER))
for b in range(4): data+=struct.pack('<3I',0x40000000|(b//2)<<16|(b%2)<<8,0xffe00000,31)
assert len(data)==72
data+=code+canary
data+=bytes(188-len(data))
source=(ROOT/'src/records_original.h').read_text()
old=re.findall(r'\{(0x[0-9a-f]+)u,(0x[0-9a-f]+)u,0x[0-9a-f]+u\}',source.split('static const struct post_word post_disable')[0])
assert len(old)==47
out='/* Generated by tests/make_payload.py. */\nstruct post_word { uint32_t address, old_value, new_value; };\nstatic struct post_word post_words[] = {\n'
for n,(a,v) in enumerate(old):out+=f'{{{a}u,{v}u,0x{struct.unpack_from("<I",data,n*4)[0]:08x}u}},\n'
out+='};\n'+source[source.index('static const struct post_word post_disable'):]
new=struct.unpack('<I',jump(0x2c28c,START)+bytes.fromhex('47'))[0]
out=out.replace('0x472a8306u',f'0x{new:08x}u')
out+=f'\n#define POST_START 0x{START:x}u\n#define POST_CANARY_FN 0x{CANARY_FN:x}u\n#define POST_COUNTER 0x{COUNTER:x}u\n'
(ROOT/'src/records.h').write_text(out)
(ROOT/'evidence/payload.bin').write_bytes(data)
(ROOT/'evidence/layout.json').write_text(json.dumps(dict(base=BASE,start=START,canary=CANARY_FN,counter=COUNTER,end=END,bytes=188,table=BASE+24,code_bytes=len(code)),indent=2)+'\n')
print(dict(start=hex(START),canary=hex(CANARY_FN),counter=hex(COUNTER),code_bytes=len(code)))
