#!/usr/bin/env python3
"""Reproduce entry-less MMIO callbacks in the owned 188-byte 2E region."""
import struct,json,re
from pathlib import Path
ROOT=Path(__file__).resolve().parents[1];BASE=0x36c7c
def i24(v):return v.to_bytes(3,'little')
def lr(pc,r,dst):
 d=dst-((pc+3)&~3);assert d%4==0 and -0x40000<=d<0
 return i24(1|r<<4|((d//4)&65535)<<8)
code=bytearray();READ=BASE+16
def emit(b):code.extend(b)
def literal(r,n):emit(lr(READ+len(code),r,BASE+4*n))
def memw():emit(bytes.fromhex('c02000'))
def count_return():
 literal(8,3);emit(bytes.fromhex('98081b999908'));memw();emit(bytes.fromhex('1df0'))
literal(8,0);memw();emit(bytes.fromhex('9808'));literal(8,2);emit(bytes.fromhex('9908'));memw();count_return()
while len(code)%4:emit(b'\0')
WRITE=READ+len(code)
literal(8,0);literal(9,1);memw();emit(bytes.fromhex('926800'));memw();count_return()
while len(code)%4:emit(b'\0')
PROBE=READ+len(code);count_return()
while len(code)%4:emit(b'\0')
RESULT=BASE+176;COUNT=BASE+180
assert READ+len(code)<=RESULT
source=(ROOT/'src/records_original.h').read_text()
words=re.findall(r'\{(0x[0-9a-f]+)u,(0x[0-9a-f]+)u,0x[0-9a-f]+u\}',source.split('static const struct post_word post_disable')[0])
data=bytearray().join(struct.pack('<I',int(v,16)) for a,v in words)
data[:16]=struct.pack('<4I',0,0,RESULT,COUNT)
data[16:16+len(code)]=code
struct.pack_into('<II',data,176,0,0)
out='/* Generated by tests/make_reader.py; same original 188-byte region. */\nstatic const uint32_t gpu_reader_words[47] = {\n'
out+=''.join(f'0x{struct.unpack_from("<I",data,n*4)[0]:08x}u,\n' for n in range(47))+'};\n'
for name,value in [('READ',READ),('WRITE',WRITE),('PROBE',PROBE),('RESULT',RESULT),('COUNT',COUNT)]:out+=f'#define GPU_{name} 0x{value:x}u\n'
(ROOT/'src/gpu_reader.h').write_text(out);(ROOT/'evidence/reader.bin').write_bytes(data)
(ROOT/'evidence/reader-layout.json').write_text(json.dumps(dict(base=BASE,read=READ,write=WRITE,probe=PROBE,result=RESULT,count=COUNT,code_bytes=len(code)),indent=2)+'\n')
print(dict(read=hex(READ),write=hex(WRITE),probe=hex(PROBE),bytes=len(data)))
